# Generated by Django 4.0.6 on 2022-07-23 14:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 23, 14, 31, 35, 604986, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
