# Generated by Django 4.0.6 on 2022-07-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='ade', max_length=255),
            preserve_default=False,
        ),
    ]
